### PR TITLE
Get the result of the create-upload command as JSON

### PR DESCRIPTION
**Pull request by otusweb**
- Get the result of the create-upload command as JSON 
- use python JSON parser to parse the response from the create-upload command instead of using cut

### CODE REVIEW

**Review by fadookie — COMMENTED** [review]
Thanks for the PR. However I don't agree that these changes are necessary. I think it's safe to assume that neither the ARN or the URL will have a space literal in them. Invoking a different interpreter will make this step run a bit slower, and introduce another dependency. If you feel strongly about this change please make an argument for it.

**Comment by fadookie** [comment]
Also the order of the response variables should be guaranteed due to my JMESPath query.

**Review by fadookie — CHANGES_REQUESTED** [review]
See above.

**Comment by otusweb** [comment]
While it is safe to assume for now don't have a space, what happens if the query returns an error. With JSOn parser, you'll get the error bubbled right away. where I believe that with the current code, it will most likely fail silently. 
As for running slower, you're probably right, but i doubt that it is in a measurably significant way.

**Comment by fadookie** [comment]
@otusweb JMESPath syntax errors will cause awscli to exit nonzero, causing the step to fail immediately. However I tried a syntactically correct nonsense query and you are correct that it does not raise an error. In text mode however, it will cause the query to return `None`. So how about this... I can add an explicit check if the first field is equal to `None` at which point the step will fail.

example:

```
$ aws devicefarm list-projects --query='foo['

Bad value for --query foo[: Invalid jmespath expression: Incomplete expression:
"foo["
     ^
$ echo $?
255
$ aws devicefarm list-projects --query='foobar' --output=text
None
```

**Comment by evaneos-mobile-integration-continue** [comment]
Sounds good. Thanks for considering!

**Comment by otusweb** [comment]
Sounds good. Thanks for considering!

**Comment by fadookie** [comment]
@otusweb Of course! Feel free to send more PRs in the future regarding the other issue you opened or whatever.

**Pull request closed without merging**
